#!/usr/bin/env python3
import urllib.request as ur
import sys
import json

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

search_query = [i.split(' ')[0] for i in sys.argv]
search_query.pop(0)

query = ""
for i in range(0, len(search_query)):
    if i < len(search_query)-1:
        query += search_query[i] + "%20" 
    else:
        query += search_query[i]

json_p = json.loads(ur.urlopen("https://en.wikipedia.org/w/api.php?action=opensearch&redirects=resolve&format=json&search=" + query).read())
link_dict = {}

if len(json_p[1]) != 0:
    if "may refer to:" in json_p[2][0]:
        json_p[1].pop(0)
        json_p[2].pop(0)
        json_p[3].pop(0)

    for i in range(0, len(json_p[1])):
        link_dict[i] = json_p[2][i]
        print("(" + str(i) + ")", json_p[1][i])

    print()

    while True:
        try:
            inp = input(color.BLUE + "Which of these are you interested in? " + color.END)
            inp = int(inp)
            if (inp >= 0 and inp < len(json_p[1])):
                break
        except ValueError:
            print('Invalid Entry, please enter a valid number')

    print()
    print(color.BOLD + json_p[1][inp] + color.END)
    print(link_dict[inp])
    print()
    print("More information", color.UNDERLINE + json_p[3][inp] + color.END)
else:
    print(color.RED + "Sorry, nothing was found under '" + " ".join(search_query) + "'" + color.END)
